apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /data/postgres-pv

